{{- if .Values.settingsJob.enabled }}
# Job to apply settings immediately on deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-settings-job
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    {{ include "settings-pod" . | indent 4 }}
{{- end }}