name: Test GitLab UDS capability

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:

      - name: Fail if Draft PR
        if: github.event.pull_request.draft == true
        run: exit 1

      - uses: actions/checkout@v3

      - name: Init zarf cache
        uses: actions/cache@v3
        with:
          path: "~/.zarf-cache"
          key: zarf-cache

      - name: Install zarf
        uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/defenseunicorns/zarf/releases/download/v0.28.0/zarf_v0.28.0_Linux_amd64'
          name: 'zarf'
          version: 'v0.28.0'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      - name: Create k3d cluster
        id: create-cluster
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.3
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: Download zarf init package
        run: zarf tools download-init --no-progress

      - name: Deploy zarf init package
        run: zarf init -a amd64 --components=git-server --confirm

      - name: Deploy DUBBD on k3d cluster
        run: zarf package deploy oci://ghcr.io/defenseunicorns/packages/dubbd-k3d:0.3.0-amd64 --no-progress --confirm
        timeout-minutes: 60

      - name: Build gitlab package
        run: zarf package create --confirm --no-progress --output test/

      - name: Deploy gitlab package
        run: zarf package deploy zarf-package-gitlab-amd64-*.tar.zst --no-progress --confirm
        working-directory: test

      - name: Wait for gitlab webservice deployment to exist
        run: timeout 1200 bash -c "while ! kubectl get deployment gitlab-gitlab-webservice-default -n gitlab; do sleep 5; done"

      - name: Wait for gitlab webservice deployment to be ready
        run: kubectl rollout status deployment/gitlab-gitlab-webservice-default -n gitlab --watch --timeout=1200s

      - name: Teardown k3d cluster
        if: always()
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.3
        with:
          cluster-action: destroy