name: Test Build and Test on ARM64

on:
  push:
    branches:
      - ewyles/pre-release-testing

jobs:
  publish-package:
    runs-on: ${{ matrix.architecture == 'arm64' && 'uds-ubuntu-arm64-4-core' || 'ubuntu-latest' }}
    strategy:
      matrix:
        flavor: [upstream, registry1]
        architecture: [amd64, arm64]
        exclude:
          - flavor: registry1
            architecture: arm64
    name: Publish ${{ matrix.flavor }} ${{ matrix.architecture }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@4cea6c8858b9f4db3a3624a6fc046db77e1f4eaa # v0.5.0
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package
        run: UDS_ARCHITECTURE=${{ matrix.architecture }} uds run -f tasks/ewyles-temp.yaml package --set FLAVOR=${{ matrix.flavor }}

      - name: Debug Output
        if: ${{ always() }}
        uses: defenseunicorns/uds-common/.github/actions/debug-output@4cea6c8858b9f4db3a3624a6fc046db77e1f4eaa # v0.5.0

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@4cea6c8858b9f4db3a3624a6fc046db77e1f4eaa # v0.5.0
        with:
          suffix: '${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}'
